In [25]:
import pandas as pd

## Step-1:: Read the csv file using pandas and store it in a variable called df.
df=pd.read_csv("matches.csv")
df.head(5) # we can use tail() to see the last 5 rows of the dataframe.

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [26]:

df.shape
df.info() #Understanding Dataset Structure
df.describe() #Statistical Summary

<class 'pandas.DataFrame'>
RangeIndex: 636 entries, 0 to 635
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               636 non-null    int64
 1   season           636 non-null    int64
 2   city             629 non-null    str
 3   date             636 non-null    str
 4   team1            636 non-null    str
 5   team2            636 non-null    str
 6   toss_winner      636 non-null    str
 7   toss_decision    636 non-null    str
 8   result           636 non-null    str
 9   dl_applied       636 non-null    int64
 10  winner           633 non-null    str
 11  win_by_runs      636 non-null    int64
 12  win_by_wickets   636 non-null    int64
 13  player_of_match  633 non-null    str
 14  venue            636 non-null    str
 15  umpire1          635 non-null    str
 16  umpire2          635 non-null    str
 17  umpire3          0 non-null      float64
dtypes: float64(1), int64(5), str(12)
memory usage: 89.6 KB

,id,season,dl_applied,win_by_runs,win_by_wickets,umpire3
count,636.000000,636.000000,636.000000,636.000000,636.000000,0.0
mean,318.500000,2012.490566,0.025157,13.682390,3.372642,NaN
std,183.741666,2.773026,0.156726,23.908877,3.420338,NaN
min,1.000000,2008.000000,0.000000,0.000000,0.000000,NaN
25%,159.750000,2010.000000,0.000000,0.000000,0.000000,NaN
50%,318.500000,2012.000000,0.000000,0.000000,4.000000,NaN
75%,477.250000,2015.000000,0.000000,20.000000,7.000000,NaN
max,636.000000,2017.000000,1.000000,146.000000,10.000000,NaN

In [27]:
df["winner"] ## single column
df[["winner","season"]] ## multiple columns

                          winner  season
0            Sunrisers Hyderabad    2017
1         Rising Pune Supergiant    2017
2          Kolkata Knight Riders    2017
3                Kings XI Punjab    2017
4    Royal Challengers Bangalore    2017
..                           ...     ...
631  Royal Challengers Bangalore    2016
632  Royal Challengers Bangalore    2016
633          Sunrisers Hyderabad    2016
634          Sunrisers Hyderabad    2016
635          Sunrisers Hyderabad    2016

[636 rows x 2 columns]

In [28]:
df["season"].value_counts() #Find Matches Per Season

season
2013    76
2012    74
2011    73
2010    60
2014    60
2016    60
2017    59
2015    59
2008    58
2009    57
Name: count, dtype: int64

In [29]:
df["winner"].value_counts().head(1) #Most winning Team

winner
Mumbai Indians    92
Name: count, dtype: int64

In [30]:
df[df["venue"] == "Holkar Cricket Stadium"]

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
7,8,2017,Indore,2017-04-10,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,normal,0,Kings XI Punjab,0,8,AR Patel,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
21,22,2017,Indore,2017-04-20,Kings XI Punjab,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,8,JC Buttler,Holkar Cricket Stadium,M Erasmus,C Shamshuddin,NaN
289,290,2011,Indore,2011-05-13,Kochi Tuskers Kerala,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,KD Karthik,Holkar Cricket Stadium,S Asnani,RJ Tucker,NaN
293,294,2011,Indore,2011-05-15,Rajasthan Royals,Kochi Tuskers Kerala,Kochi Tuskers Kerala,field,normal,0,Kochi Tuskers Kerala,0,8,BJ Hodge,Holkar Cricket Stadium,PR Reiffel,RJ Tucker,NaN

In [31]:
df["player_of_match"].value_counts().head(5) #Top 5 players with most player of the match awards

player_of_match
CH Gayle          18
YK Pathan         16
DA Warner         15
AB de Villiers    15
SK Raina          14
Name: count, dtype: int64

In [32]:
df.isnull() # to check for null values in the dataset
cleaned_df = df.dropna()

In [33]:
cleaned_df.isnull().sum() # to get the count of null values in each column

id                 0
season             0
city               0
date               0
team1              0
team2              0
toss_winner        0
toss_decision      0
result             0
dl_applied         0
winner             0
win_by_runs        0
win_by_wickets     0
player_of_match    0
venue              0
umpire1            0
umpire2            0
umpire3            0
dtype: int64

In [34]:
## Bonus tasks:
###batting first
bat_first = df[df["toss_decision"] == "bat"]
bat_first["winner"].value_counts()

winner
Chennai Super Kings            50
Mumbai Indians                 41
Kolkata Knight Riders          34
Rajasthan Royals               30
Delhi Daredevils               28
Royal Challengers Bangalore    26
Kings XI Punjab                20
Sunrisers Hyderabad            16
Deccan Chargers                14
Pune Warriors                   9
Rising Pune Supergiants         2
Gujarat Lions                   2
Name: count, dtype: int64

In [35]:
field_first = df[df["toss_decision"] == "field"]
field_first["winner"].value_counts()

winner
Mumbai Indians                 51
Kings XI Punjab                50
Royal Challengers Bangalore    47
Kolkata Knight Riders          43
Delhi Daredevils               34
Rajasthan Royals               33
Chennai Super Kings            29
Sunrisers Hyderabad            26
Deccan Chargers                15
Gujarat Lions                  11
Rising Pune Supergiant         10
Kochi Tuskers Kerala            6
Pune Warriors                   3
Rising Pune Supergiants         3
Name: count, dtype: int64